<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-15 at 15:12:47.
 */
require_once  __DIR__ . '/bootstrap.php';

class KismaTest extends \Kisma\Core\TestCase
{
	/**
	 * @var \Kisma
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new \Kisma\Core\Services\Storage();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Kisma::conceive
	 */
	public function testConceive()
	{
	}

	/**
	 * @covers Kisma::getAutoLoader
	 */
	public function testGetAutoLoader()
	{
		$this->assertInstanceOf( '\\Composer\\Autoload\\ClassLoader', \Kisma::getAutoLoader() );
	}

	/**
	 * @covers Kisma::getBasePath
	 */
	public function testGetBasePath()
	{
		$this->assertTrue( dirname( __DIR__ ) . '/src' == \Kisma::getBasePath() );
	}

	/**
	 * @covers Kisma::set
	 * @covers Kisma::get
	 */
	public function testSet()
	{
		\Kisma::set( 'testSetOption', true );
		$this->assertTrue( \Kisma::get( 'testSetOption' ) );
	}

	/**
	 * @covers Kisma::get
	 */
	public function testGet()
	{
		$this->assertTrue( \Kisma::get( 'testSetOption' ) );
	}

	/**
	 * @covers Kisma::setOptions
	 */
	public function testSetOptions()
	{
		$this->assertTrue( is_array( $_options = \Kisma::getOptions() ) );
		$_options['testSetOption2'] = true;
		\Kisma::setOptions( $_options );

		$this->assertTrue( \Kisma::get( 'testSetOption2', false ) );
	}

	/**
	 * @covers Kisma::getOptions
	 */
	public function testGetOptions()
	{
		$this->assertTrue( is_array( $_options = \Kisma::getOptions() ) );
		$this->assertArrayHasKey( \Kisma\Core\Utility\Inflector::tag( 'testSetOption', true ), $_options );
	}
}
