<?php
namespace Kisma\Core\Utility;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-08-18 at 16:17:01.
 */
class CouchDbClientTest extends \Kisma\Core\TestCase
{
	/**
	 * @var CouchDbClient
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = ChairLift::couchDbClient(
			array(
				'host_name'     => 'japhrimel',
				'user_name'     => 'kisma',
				'password'      => 'kisma',
				'database_name' => 'kisma_test_couch_db_client'
			)
		);

		$_view = $this->object->getView( 'by_date' );
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Kisma\Core\Utility\CouchDbClient::serverExists
	 */
	public function testServerExists()
	{
		$this->assertTrue( $this->object->serverExists() );
	}

	/**
	 * @covers Kisma\Core\Utility\CouchDbClient::databaseExists
	 */
	public function testDatabaseExists()
	{
		$this->assertTrue( false !== $this->object->databaseExists( 'kisma_test_couch_db_client' ) );
	}

	/**
	 * @covers Kisma\Core\Utility\CouchDbClient::documentExists
	 * @todo   Implement testDocumentExists().
	 */
	public function testDocumentExists()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kisma\Core\Utility\CouchDbClient::getRevsLimit
	 * @todo   Implement testGetRevsLimit().
	 */
	public function testGetRevsLimit()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kisma\Core\Utility\CouchDbClient::changes
	 * @todo   Implement testChanges().
	 */
	public function testChanges()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kisma\Core\Utility\CouchDbClient::getView
	 * @todo   Implement testGetView().
	 */
	public function testGetView()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kisma\Core\Utility\CouchDbClient::getAttachment
	 * @todo   Implement testGetAttachment().
	 */
	public function testGetAttachment()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kisma\Core\Utility\CouchDbClient::bulk
	 * @todo   Implement testBulk().
	 */
	public function testBulk()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kisma\Core\Utility\CouchDbClient::copyById
	 * @todo   Implement testCopyById().
	 */
	public function testCopyById()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kisma\Core\Utility\CouchDbClient::create
	 * @todo   Implement testCreate().
	 */
	public function testCreate()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kisma\Core\Utility\CouchDbClient::setDatabaseName
	 * @todo   Implement testSetDatabaseName().
	 */
	public function testSetDatabaseName()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kisma\Core\Utility\CouchDbClient::getDatabaseName
	 * @todo   Implement testGetDatabaseName().
	 */
	public function testGetDatabaseName()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kisma\Core\Utility\CouchDbClient::setHostName
	 * @todo   Implement testSetHostName().
	 */
	public function testSetHostName()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kisma\Core\Utility\CouchDbClient::getHostName
	 * @todo   Implement testGetHostName().
	 */
	public function testGetHostName()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
