<?php
require_once '/opt/kisma/Kisma.php';

/*
 * @method SimpleXMLElement transform( $value, $options = array() )
 */
class TestComponent extends \Kisma\Components\Component
{
	protected $_testData = array();

	public function __construct( $options = array() )
	{
		parent::__construct( $options );
		$this->linkAspect( 'kisma.aspects.transform.Xml' );
		$this->linkAspect( 'kisma.aspects.transform.Json' );
	}

	public function setTestData( $testData )
	{
		$this->_testData = $testData;
		return $this;
	}

	public function getTestData()
	{
		return $this->_testData;
	}
}

/**
 * Test class for Component.
 * Generated by PHPUnit on 2011-09-19 at 21:55:10.
 */
class ComponentTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \Kisma\Components\Component
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		$_options = array(
			'testData' => array(
				'subArray' => array(
					'key1' => 'value1',
					'key2' => 'value2',
					'key3' => 3,
				),
				'stringValue' => 'string',
				'intValue' => 666,
				'floatValue' => 6.66,
				'objectValue' => $this->object,
			),
		);

        $this->object = new TestComponent( $_options );
    }

    /**
     * @todo Implement testBind().
     */
    public function testTransform()
    {
		$_data = $this->object->getTestData();
		$_xml = $this->object->toXml( $_data );
		$_json = $this->object->toJson( $_data );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

}
