<?php
namespace Kisma\Core\Utility;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-16 at 21:20:12.
 */
class OptionTest extends \PHPUnit_Framework_TestCase
{
	/**
	 * @var Option
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Option;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Kisma\Core\Utility\Option::get
	 * @todo   Implement testGet().
	 */
	public function testGet()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kisma\Core\Utility\Option::o
	 * @todo   Implement testO().
	 */
	public function testO()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kisma\Core\Utility\Option::oo
	 * @todo   Implement testOo().
	 */
	public function testOo()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kisma\Core\Utility\Option::set
	 * @todo   Implement testSet().
	 */
	public function testSet()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kisma\Core\Utility\Option::so
	 * @todo   Implement testSo().
	 */
	public function testSo()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kisma\Core\Utility\Option::unsetOption
	 * @todo   Implement testUnsetOption().
	 */
	public function testUnsetOption()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kisma\Core\Utility\Option::uo
	 * @todo   Implement testUo().
	 */
	public function testUo()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Kisma\Core\Utility\Option::merge
	 * @todo   Implement testMerge().
	 */
	public function testMerge()
	{
		$_a1 = array( 'a'=> 1, 'b'=> 2, 'c'=> 3 );
		$_a2 = array( 'd'=> 4, 'e'=> 5, 'f'=> 6 );
		$_a3 = array( 'a'=> 7, 'b'=> 8, 'c'=> 9 );
		$_a4 = array( 'p'=> 666, 'q'=> 18, 'r'=> 19 );

		$_result = Option::merge( $_a1, $_a2, $_a3, $_a4 );

		$this->assertTrue( is_array( $_result ) && $_result['a'] == 7 );
		$this->assertTrue( is_array( $_result ) && $_result['p'] == 666 );
	}
}
