<?php
/*
 * This file was generated by the yiixl scaffolding package.
 * 
 * @copyright Copyright &copy; 2009 My Company, LLC.
 * @link http://www.example.com
 */

/**
 * admin view file
 * 
 * @package 	blog
 * @subpackage 	
 * 
 * @author 		Web Master <webmaster@example.com>
 * @version 	SVN: $Id: admin.php 367 2010-01-16 04:29:24Z jerryablan@gmail.com $
 * @since 		v1.0.6
 *  
 * @filesource
 *                                                                   
 */
 	
 	//	Load our grid css
 	YiiXL::_rcf( $this->getAppBaseUrl() . '/css/grid.css' );
 
 	//	Build the header
	echo CXLHelperBase

	//	Build the grid
	$_arOpts = array(
		'actions' => array( 
			YiiXL::ACTION_GENERIC => array(
				'label' => 'Publish',
				'url' => array( 'publish', 'id' => '%%id%%' ),
				'confirm' => 'Publish this post?',
				'icon' => 'check',
			),
			YiiXL::ACTION_EDIT,
			YiiXL::ACTION_DELETE,
		),
		'sort' => $sort,
		'pages' => $pages,
		'columns' => array( 'title_text', 'statusText', ',comment_count_nbr' ),
		'pagerOptions' => array( 'header' => '' ),
		'dataItemName' => 'Post',
	);
	
	echo CXLHelperBase